name: Deploy Infrastructure (Azure VM with Terraform)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Deploy VM and SonarQube
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Get Terraform Outputs
        id: tf_outputs
        run: |
          echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
          echo "vm_admin_user=$(terraform output -raw vm_admin_user)" >> $GITHUB_OUTPUT

      - name: Save environment variables
        run: |
          echo "SONAR_HOST_URL=http://${{ steps.tf_outputs.outputs.public_ip }}:9000" >> $GITHUB_ENV
          echo "VM_USER=${{ steps.tf_outputs.outputs.vm_admin_user }}" >> $GITHUB_ENV

      - name: Verify Docker and SonarQube
        run: |
          ssh -o StrictHostKeyChecking=no $VM_USER@${{ steps.tf_outputs.outputs.public_ip }} "docker ps"
          echo "✅ Infraestructura desplegada correctamente"
